#!/bin/bash

# ================================================================
# CareerAI SaaS — Cloud Setup Helper
# ================================================================
# Generates a complete .env file ready for cloud deployment.
# Usage: ./scripts/cloud-setup.sh
# ================================================================

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}=========================================="
echo -e "  CareerAI SaaS — Cloud Setup"
echo -e "==========================================${NC}"
echo ""

# ---------------------------------------------------------------
# Generate cryptographically secure random secrets
# ---------------------------------------------------------------
generate_secret() {
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" 2>/dev/null \
        || python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
        || openssl rand -hex 32
}

echo -e "${GREEN}[1/4]${NC} Generating JWT secrets..."
JWT_ACCESS_SECRET=$(generate_secret)
JWT_REFRESH_SECRET=$(generate_secret)

# ---------------------------------------------------------------
# Prompt for required values
# ---------------------------------------------------------------
echo ""
echo -e "${GREEN}[2/4]${NC} Required configuration"
echo ""

read -rp "  MongoDB URI (Atlas: mongodb+srv://...): " MONGODB_URI
read -rp "  Frontend URL (e.g. https://career-ai.onrender.com): " FRONTEND_URL

# Derive API URL from frontend URL if not overridden
DEFAULT_API_URL="${FRONTEND_URL/frontend/backend}"
read -rp "  Backend API URL [${DEFAULT_API_URL}/api/v1]: " NEXT_PUBLIC_API_URL
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-${DEFAULT_API_URL}/api/v1}"

read -rp "  ML Service URL (e.g. https://career-ai-ml.onrender.com): " ML_SERVICE_URL

echo ""
echo -e "${GREEN}[3/4]${NC} Optional configuration (press Enter to skip)"
echo ""

read -rp "  CORS allowed origins [$FRONTEND_URL]: " CORS_ORIGIN
CORS_ORIGIN="${CORS_ORIGIN:-$FRONTEND_URL}"

read -rp "  OpenAI API key: " OPENAI_API_KEY
read -rp "  Stripe secret key: " STRIPE_SECRET_KEY
read -rp "  Stripe webhook secret: " STRIPE_WEBHOOK_SECRET

# ---------------------------------------------------------------
# Write .env file
# ---------------------------------------------------------------
ENV_FILE="$PROJECT_DIR/docker/.env"

echo ""
echo -e "${GREEN}[4/4]${NC} Writing $ENV_FILE..."

cat > "$ENV_FILE" <<EOF
# CareerAI SaaS — Cloud Environment
# Generated by scripts/cloud-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Server
NODE_ENV=production

# JWT
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# MongoDB
MONGODB_URI=${MONGODB_URI}

# URLs
CORS_ORIGIN=${CORS_ORIGIN}
FRONTEND_URL=${FRONTEND_URL}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ML_SERVICE_URL=${ML_SERVICE_URL}

# Email (update with your SMTP / SendGrid credentials)
EMAIL_PROVIDER=smtp
EMAIL_FROM_ADDRESS=noreply@careerai.com
EMAIL_FROM_NAME=CareerAI
SMTP_HOST=smtp.mailtrap.io
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=

# LLM
LLM_PROVIDER=openai
LLM_MODEL=gpt-4o-mini
OPENAI_API_KEY=${OPENAI_API_KEY}

# Stripe
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_PRO_PRICE_ID=
STRIPE_ENTERPRISE_PRICE_ID=

# Admin
ADMIN_EMAIL=admin@careerai.com
ADMIN_DEFAULT_PASSWORD=$(generate_secret | cut -c1-16)

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# File Upload
MAX_FILE_SIZE=5242880
UPLOAD_PATH=./uploads
EOF

chmod 600 "$ENV_FILE"

echo ""
echo -e "${GREEN}✅ Done!${NC}"
echo ""
echo "  📄 Configuration saved to: $ENV_FILE"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Review $ENV_FILE and add any missing values (SMTP, Stripe, etc.)"
echo "  2. Deploy with Docker Compose (production):"
echo "       make prod"
echo "  OR deploy to a cloud platform:"
echo "       Railway: https://railway.app  (uses railway.toml)"
echo "       Render:  https://render.com   (uses render.yaml)"
echo ""
